global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-datalake-sagemaker
  regions:
  - us-east-1
  reporting: true
tests:
  json-master:
    parameter_input: datalake-sagemaker.json
    regions:
      - us-east-1
    template_file: datalake-sagemaker.template